## 4. Data Collection

The dataset for this project was sourced from Kaggle, a popular platform for data science competitions and datasets. Specifically, the data can be found at [Kaggle - bluebook-for-bulldozers](https://www.kaggle.com/competitions/bluebook-for-bulldozers).

### Dataset Description

The dataset comprises information gathered from auction result postings and includes details about the usage, equipment types, and configurations of heavy equipment. The goal is to predict the sale price of this equipment at auction.

### Kaggle Source

[Kaggle](https://www.kaggle.com/) provides a diverse range of datasets and competitions, making it a valuable resource for data scientists and analysts. The platform fosters collaboration and knowledge sharing within the data science community.

### Data Access

To access the dataset for this project, you can visit the Kaggle link mentioned above and download the relevant files. Make sure to review any documentation or additional information provided on Kaggle to better understand the dataset's structure and features.


This completes the "Data Collection" step, laying the foundation for subsequent stages in our data methodology.

## 5. Data Understanding

### Column Descriptions

1. **SalesID:** Unique identifier for a particular sale of a machine at auction.
2. **MachineID:** Identifier for a particular machine; machines may have multiple sales.
3. **ModelID:** Identifier for a unique machine model (i.e., fiModelDesc).
4. **Datasource:** Source of the sale record; some sources are more diligent about reporting attributes of the machine than others. Note that a particular datasource may report on multiple auctioneerIDs.
5. **AuctioneerID:** Identifier of a particular auctioneer, i.e., the company that sold the machine at auction. Not the same as datasource.
6. **YearMade:** Year of manufacturer of the machine.
7. **MachineHoursCurrentMeter:** Current usage of the machine in hours at the time of sale (saledate); null or 0 means no hours have been reported for that sale.
8. **UsageBand:** Value (low, medium, high) calculated by comparing this particular Machine-Sale hours to average usage for the fiBaseModel; e.g., 'Low' means this machine has fewer hours given its lifespan relative to the average of fiBaseModel.
9. **SaleDate:** Time of sale.
10. **SalePrice:** Cost of sale in USD.
11. **fiModelDesc:** Description of a unique machine model (see ModelID); concatenation of fiBaseModel & fiSecondaryDesc & fiModelSeries & fiModelDescriptor.
12. **fiBaseModel:** Disaggregation of fiModelDesc.
13. **fiSecondaryDesc:** Disaggregation of fiModelDesc.
14. **fiModelSeries:** Disaggregation of fiModelDesc.
15. **fiModelDescriptor:** Disaggregation of fiModelDesc.
16. **ProductSize:** Not specified.
17. **ProductClassDesc:** Description of the 2nd level hierarchical grouping (below ProductGroup) of fiModelDesc.
18. **State:** US State in which the sale occurred.
19. **ProductGroup:** Identifier for the top-level hierarchical grouping of fiModelDesc.
20. **ProductGroupDesc:** Description of the top-level hierarchical grouping of fiModelDesc.

(Continued...)

21. **Drive_System:** Machine configuration; typically describes whether 2 or 4 wheel drive.
22. **Enclosure:** Machine configuration - does the machine have an enclosed cab or not.
23. **Forks:** Machine configuration - attachment used for lifting.
24. **Pad_Type:** Machine configuration - type of treads a crawler machine uses.
25. **Ride_Control:** Machine configuration - optional feature on loaders to make the ride smoother.
26. **Stick:** Machine configuration - type of control.
27. **Transmission:** Machine configuration - describes the type of transmission; typically automatic or manual.
28. **Turbocharged:** Machine configuration - engine naturally aspirated or turbocharged.
29. **Blade_Extension:** Machine configuration - extension of the standard blade.
30. **Blade_Width:** Machine configuration - width of the blade.
31. **Enclosure_Type:** Machine configuration - does the machine have an enclosed cab or not.
32. **Engine_Horsepower:** Machine configuration - engine horsepower rating.
33. **Hydraulics:** Machine configuration - type of hydraulics.
34. **Pushblock:** Machine configuration - option.
35. **Ripper:** Machine configuration - implement attached to the machine to till soil.
36. **Scarifier:** Machine configuration - implement attached to the machine to condition soil.
37. **Tip_Control:** Machine configuration - type of blade control.
38. **Tire_Size:** Machine configuration - size of primary tires.
39. **Coupler:** Machine configuration - type of implement interface.
40. **Coupler_System:** Machine configuration - type of implement interface.

(Continued...)

41. **Grouser_Tracks:** Machine configuration - describes ground contact interface.
42. **Hydraulics_Flow:** Machine configuration - normal or high flow hydraulic system.
43. **Track_Type:** Machine configuration - type of treads a crawler machine uses.
44. **Undercarriage_Pad_Width:** Machine configuration - width of crawler treads.
45. **Stick_Length:** Machine configuration - length of the machine digging implement.
46. **Thumb:** Machine configuration - attachment used for grabbing.
47. **Pattern_Changer:** Machine configuration - can adjust the operator control configuration to suit the user.
48. **Grouser_Type:** Machine configuration - type of treads a crawler machine uses.
49. **Backhoe_Mounting:** Machine configuration - optional interface used to add a backhoe attachment.
50. **Blade_Type:** Machine configuration - describes the type of blade.
51. **Travel_Controls:** Machine configuration - describes operator control configuration.
52. **Differential_Type:** Machine configuration - differential type, typically locking or standard.
53. **Steering_Controls:** Machine configuration - describes operator control configuration.

## Certain columns may be particularly relevant for your machine learning model

### 1. Machine Configuration
- **Drive_System:** Whether the machine is 2 or 4 wheel drive.
- **Forks:** Attachment used for lifting.
- **Ride_Control:** Optional feature on loaders to make the ride smoother.
- **Transmission:** Describes the type of transmission (automatic or manual).
- **Turbocharged:** Indicates if the engine is naturally aspirated or turbocharged.
- **Hydraulics_Flow:** Normal or high flow hydraulic system.
- **Backhoe_Mounting:** Optional interface used to add a backhoe attachment.
- **Blade_Type:** Describes the type of blade.

### 2. Machine Condition and Features
- **Enclosure_Type:** Specifies if the machine has an enclosed cab or not.
- **ProductSize:** Description of the size or capacity of the machine.
- **Engine_Horsepower:** Engine horsepower rating.
- **Pattern_Changer:** Ability to adjust the operator control configuration.

### 3. Machine Usage and Accessories
- **MachineHoursCurrentMeter:** Current usage of the machine in hours at the time of sale.
- **UsageBand:** Value (low, medium, high) comparing machine-sale hours to average usage.

### 4. Geographical and Temporal Information
- **State:** U.S. state in which the sale occurred.
- **SaleDate:** The time of sale. Extracting features like month or season could reveal temporal patterns.

### 5. Auction and Vendor Information
- **AuctioneerID:** Identifier of the auctioneer or company that sold the machine.
- **Datasource:** Source of the sale record.

### 6. Additional Machine Specifications
- **ProductClassDesc:** Description of the 2nd level hierarchical grouping.
- **ProductGroup:** Identifier for the top-level hierarchical grouping.
- **ProductGroupDesc:** Description of the top-level hierarchical grouping.
- **Tip_Control:** Type of blade control.
- **Tire_Size:** Size of primary tires.

Remember to continuously assess the impact of each feature on the target variable (SalePrice) during your analysis. Exploratory Data Analysis (EDA) and feature importance techniques can help you uncover hidden patterns and identify influential features in your dataset. Adjust your feature selection based on insights gained during the preprocessing and analysis phases.

In [8]:
import pandas as pd

In [9]:
# we first will understand the data first 
df = pd.read_csv("Train.csv")

<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\ELBOSTAN\AppData\Local\Temp\ipykernel_16980\3893407446.py:2: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv("D:\Data_Scientist\Bulldozers_Price_Prediction\Data\Train.csv")
C:\Users\ELBOSTAN\AppData\Local\Temp\ipykernel_16980\3893407446.py:2: DtypeWarning: Columns (13,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("D:\Data_Scientist\Bulldozers_Price_Prediction\Data\Train.csv")

In [7]:
# see how the data is 
df.select_dtypes(exclude=['int', 'float']).head()

,UsageBand,saledate,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,ProductSize,fiProductClassDesc,state,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,Low,11/16/2006 0:00,521D,521,D,NaN,NaN,NaN,Wheel Loader - 110.0 to 120.0 Horsepower,Alabama,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,Low,3/26/2004 0:00,950FII,950,F,II,NaN,Medium,Wheel Loader - 150.0 to 175.0 Horsepower,North Carolina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,High,2/26/2004 0:00,226,226,NaN,NaN,NaN,NaN,Skid Steer Loader - 1351.0 to 1601.0 Lb Operat...,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,High,5/19/2011 0:00,PC120-6E,PC120,NaN,-6E,NaN,Small,"Hydraulic Excavator, Track - 12.0 to 14.0 Metr...",Texas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Medium,7/23/2009 0:00,S175,S175,NaN,NaN,NaN,NaN,Skid Steer Loader - 1601.0 to 1751.0 Lb Operat...,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Machine Configuration
machine_configuration_cols = [
    'Drive_System', 'Forks', 'Ride_Control', 'Transmission',
    'Turbocharged', 'Hydraulics_Flow', 'Backhoe_Mounting', 'Blade_Type'
]

# Machine Condition and Features
machine_condition_cols = [
    'Enclosure_Type', 'ProductSize', 'Engine_Horsepower', 'Pattern_Changer'
]

# Machine Usage and Accessories
machine_usage_cols = ['MachineHoursCurrentMeter', 'UsageBand']

# Geographical and Temporal Information
geographical_temporal_cols = ['State', 'SaleDate']

# Auction and Vendor Information
auction_vendor_cols = ['AuctioneerID', 'Datasource']

# Additional Machine Specifications
additional_spec_cols = [
    'ProductClassDesc', 'ProductGroup', 'ProductGroupDesc',
    'Tip_Control', 'Tire_Size'
]

# Combine all columns into a single list
additional_columns_to_consider = (
    machine_configuration_cols + machine_condition_cols +
    machine_usage_cols + geographical_temporal_cols +
    auction_vendor_cols + additional_spec_cols
)

In [7]:
# see the shape of the dataset 
df.shape

(401125, 53)

In [8]:
# see how it contain nulls
df.isnull().sum()

SalesID                          0
SalePrice                        0
MachineID                        0
ModelID                          0
datasource                       0
auctioneerID                 20136
YearMade                         0
MachineHoursCurrentMeter    258360
UsageBand                   331486
saledate                         0
fiModelDesc                      0
fiBaseModel                      0
fiSecondaryDesc             137191
fiModelSeries               344217
fiModelDescriptor           329206
ProductSize                 210775
fiProductClassDesc               0
state                            0
ProductGroup                     0
ProductGroupDesc                 0
Drive_System                296764
Enclosure                      325
Forks                       209048
Pad_Type                    321991
Ride_Control                252519
Stick                       321991
Transmission                217895
Turbocharged                321991
Blade_Extension             375906
Blade_Width                 375906
Enclosure_Type              375906
Engine_Horsepower           375906
Hydraulics                   80555
Pushblock                   375906
Ripper                      296988
Scarifier                   375895
Tip_Control                 375906
Tire_Size                   306407
Coupler                     187173
Coupler_System              357667
Grouser_Tracks              357763
Hydraulics_Flow             357763
Track_Type                  301972
Undercarriage_Pad_Width     301253
Stick_Length                301907
Thumb                       301837
Pattern_Changer             301907
Grouser_Type                301972
Backhoe_Mounting            322453
Blade_Type                  321292
Travel_Controls             321291
Differential_Type           331714
Steering_Controls           331756
dtype: int64

In [9]:
# lets see how is the data types 
df.dtypes

SalesID                       int64
SalePrice                     int64
MachineID                     int64
ModelID                       int64
datasource                    int64
auctioneerID                float64
YearMade                      int64
MachineHoursCurrentMeter    float64
UsageBand                    object
saledate                     object
fiModelDesc                  object
fiBaseModel                  object
fiSecondaryDesc              object
fiModelSeries                object
fiModelDescriptor            object
ProductSize                  object
fiProductClassDesc           object
state                        object
ProductGroup                 object
ProductGroupDesc             object
Drive_System                 object
Enclosure                    object
Forks                        object
Pad_Type                     object
Ride_Control                 object
Stick                        object
Transmission                 object
Turbocharged                 object
Blade_Extension              object
Blade_Width                  object
Enclosure_Type               object
Engine_Horsepower            object
Hydraulics                   object
Pushblock                    object
Ripper                       object
Scarifier                    object
Tip_Control                  object
Tire_Size                    object
Coupler                      object
Coupler_System               object
Grouser_Tracks               object
Hydraulics_Flow              object
Track_Type                   object
Undercarriage_Pad_Width      object
Stick_Length                 object
Thumb                        object
Pattern_Changer              object
Grouser_Type                 object
Backhoe_Mounting             object
Blade_Type                   object
Travel_Controls              object
Differential_Type            object
Steering_Controls            object
dtype: object

As we see most of the cols i object datatype

In [19]:
# we will drop all non values to do some EDA
# we see the columns which have more than 100000 row with non value and drop it and then drop the non row
# Threshold for null values (100,000 rows)
threshold = 100000

# Drop columns with null values exceeding the threshold
df_cleaned = df.dropna(thresh=len(df) - threshold, axis=1)

# Display the cleaned DataFrame
df_cleaned

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,saledate,fiModelDesc,fiBaseModel,fiProductClassDesc,state,ProductGroup,ProductGroupDesc,Enclosure,Hydraulics
0,1139246,66000,999089,3157,121,3.0,2004,11/16/2006 0:00,521D,521,Wheel Loader - 110.0 to 120.0 Horsepower,Alabama,WL,Wheel Loader,EROPS w AC,2 Valve
1,1139248,57000,117657,77,121,3.0,1996,3/26/2004 0:00,950FII,950,Wheel Loader - 150.0 to 175.0 Horsepower,North Carolina,WL,Wheel Loader,EROPS w AC,2 Valve
2,1139249,10000,434808,7009,121,3.0,2001,2/26/2004 0:00,226,226,Skid Steer Loader - 1351.0 to 1601.0 Lb Operat...,New York,SSL,Skid Steer Loaders,OROPS,Auxiliary
3,1139251,38500,1026470,332,121,3.0,2001,5/19/2011 0:00,PC120-6E,PC120,"Hydraulic Excavator, Track - 12.0 to 14.0 Metr...",Texas,TEX,Track Excavators,EROPS w AC,2 Valve
4,1139253,11000,1057373,17311,121,3.0,2007,7/23/2009 0:00,S175,S175,Skid Steer Loader - 1601.0 to 1751.0 Lb Operat...,New York,SSL,Skid Steer Loaders,EROPS,Auxiliary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,11/2/2011 0:00,35NX2,35,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...",Maryland,TEX,Track Excavators,EROPS,Auxiliary
401121,6333337,11000,1830472,21439,149,1.0,2005,11/2/2011 0:00,35NX2,35,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...",Maryland,TEX,Track Excavators,EROPS,Standard
401122,6333338,11500,1887659,21439,149,1.0,2005,11/2/2011 0:00,35NX2,35,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...",Maryland,TEX,Track Excavators,EROPS,Auxiliary
401123,6333341,9000,1903570,21435,149,2.0,2005,10/25/2011 0:00,30NX,30,"Hydraulic Excavator, Track - 2.0 to 3.0 Metric...",Florida,TEX,Track Excavators,EROPS,Standard
401124,6333342,7750,1926965,21435,149,2.0,2005,10/25/2011 0:00,30NX,30,"Hydraulic Excavator, Track - 2.0 to 3.0 Metric...",Florida,TEX,Track Excavators,EROPS,Standard

In [23]:
df_with_out_null = df_cleaned.dropna(axis=0)
df_with_out_null

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,saledate,fiModelDesc,fiBaseModel,fiProductClassDesc,state,ProductGroup,ProductGroupDesc,Enclosure,Hydraulics
0,1139246,66000,999089,3157,121,3.0,2004,11/16/2006 0:00,521D,521,Wheel Loader - 110.0 to 120.0 Horsepower,Alabama,WL,Wheel Loader,EROPS w AC,2 Valve
1,1139248,57000,117657,77,121,3.0,1996,3/26/2004 0:00,950FII,950,Wheel Loader - 150.0 to 175.0 Horsepower,North Carolina,WL,Wheel Loader,EROPS w AC,2 Valve
2,1139249,10000,434808,7009,121,3.0,2001,2/26/2004 0:00,226,226,Skid Steer Loader - 1351.0 to 1601.0 Lb Operat...,New York,SSL,Skid Steer Loaders,OROPS,Auxiliary
3,1139251,38500,1026470,332,121,3.0,2001,5/19/2011 0:00,PC120-6E,PC120,"Hydraulic Excavator, Track - 12.0 to 14.0 Metr...",Texas,TEX,Track Excavators,EROPS w AC,2 Valve
4,1139253,11000,1057373,17311,121,3.0,2007,7/23/2009 0:00,S175,S175,Skid Steer Loader - 1601.0 to 1751.0 Lb Operat...,New York,SSL,Skid Steer Loaders,EROPS,Auxiliary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,11/2/2011 0:00,35NX2,35,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...",Maryland,TEX,Track Excavators,EROPS,Auxiliary
401121,6333337,11000,1830472,21439,149,1.0,2005,11/2/2011 0:00,35NX2,35,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...",Maryland,TEX,Track Excavators,EROPS,Standard
401122,6333338,11500,1887659,21439,149,1.0,2005,11/2/2011 0:00,35NX2,35,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...",Maryland,TEX,Track Excavators,EROPS,Auxiliary
401123,6333341,9000,1903570,21435,149,2.0,2005,10/25/2011 0:00,30NX,30,"Hydraulic Excavator, Track - 2.0 to 3.0 Metric...",Florida,TEX,Track Excavators,EROPS,Standard
401124,6333342,7750,1926965,21435,149,2.0,2005,10/25/2011 0:00,30NX,30,"Hydraulic Excavator, Track - 2.0 to 3.0 Metric...",Florida,TEX,Track Excavators,EROPS,Standard

In [25]:
df_with_out_null.to_csv("train_without_null.csv", index=False)

In [26]:
df_with_out_null.columns

Index(['SalesID', 'SalePrice', 'MachineID', 'ModelID', 'datasource',
       'auctioneerID', 'YearMade', 'saledate', 'fiModelDesc', 'fiBaseModel',
       'fiProductClassDesc', 'state', 'ProductGroup', 'ProductGroupDesc',
       'Enclosure', 'Hydraulics'],
      dtype='object')

In [27]:
import pandas as pd

# Assuming your DataFrame is named 'df'
# You can replace 'df' with the actual name of your DataFrame

# List of columns to analyze
columns_to_analyze = ['SalesID', 'SalePrice', 'MachineID', 'ModelID', 'datasource',
                      'auctioneerID', 'YearMade', 'saledate', 'fiModelDesc', 'fiBaseModel',
                      'fiProductClassDesc', 'state', 'ProductGroup', 'ProductGroupDesc',
                      'Enclosure', 'Hydraulics']

# Create a subset DataFrame with only the selected columns
subset_df = df_with_out_null[columns_to_analyze]

# Calculate correlation coefficients for numerical columns
numerical_columns = subset_df.select_dtypes(include=['int64', 'float64']).columns
correlation_matrix = subset_df[numerical_columns].corr()

# Display correlation coefficients with SalePrice
correlation_matrix['SalePrice'].sort_values(ascending=False)

SalePrice       1.000000
YearMade        0.177561
datasource      0.013881
SalesID         0.000163
auctioneerID   -0.041633
ModelID        -0.077088
MachineID      -0.238314
Name: SalePrice, dtype: float64

In [28]:
# Perform ANOVA for categorical columns
categorical_columns = subset_df.select_dtypes(include=['object']).columns

for col in categorical_columns:
    group_means = subset_df.groupby(col)['SalePrice'].mean()
    print(f"\nANOVA for {col}:")
    print(group_means)

# You may also want to visualize the results using plots or other statistical tests.

ANOVA for saledate:
saledate
1/10/2003 0:00    14916.666667
1/10/2005 0:00    61000.000000
1/10/2008 0:00    30074.324324
1/10/2009 0:00    25958.333333
1/10/2011 0:00    75250.000000
                      ...
9/9/2005 0:00     51119.565217
9/9/2006 0:00     33240.769231
9/9/2008 0:00     37713.114754
9/9/2009 0:00     35145.205479
9/9/2010 0:00     28604.411765
Name: SalePrice, Length: 3830, dtype: float64

ANOVA for fiModelDesc:
fiModelDesc
100C        9882.352941
104         8500.000000
1066       15875.000000
1066E      17000.000000
1080       18576.136364
               ...
ZX80       37100.000000
ZX800      87611.111111
ZX800LC    67500.000000
ZX80LCK    27000.000000
ZX850H     60000.000000
Name: SalePrice, Length: 4524, dtype: float64

ANOVA for fiBaseModel:
fiBaseModel
10       13200.000000
100       9882.352941
104       8500.000000
1066     15934.210526
1080     17090.000000
             ...
ZX70     35078.947368
ZX75     31804.347826
ZX80     35416.666667
ZX800    83954.545455
ZX850    60000.000000
Name: SalePrice, Length: 1833, dtype: float64

ANOVA for fiProductClassDesc:
fiProductClassDesc
Hydraulic Excavator, Track - 0.0 to 2.0 Metric Tons        10916.918605
Hydraulic Excavator, Track - 11.0 to 12.0 Metric Tons      27672.577977
Hydraulic Excavator, Track - 12.0 to 14.0 Metric Tons      31205.024082
Hydraulic Excavator, Track - 14.0 to 16.0 Metric Tons      40157.205453
Hydraulic Excavator, Track - 150.0 to 300.0 Metric Tons    38714.285714
                                                               ...
Wheel Loader - 500.0 to 1000.0 Horsepower                  43703.557592
Wheel Loader - 60.0 to 80.0 Horsepower                     17345.566941
Wheel Loader - 80.0 to 90.0 Horsepower                     17793.885870
Wheel Loader - 90.0 to 100.0 Horsepower                    19389.377859
Wheel Loader - Unidentified                                13752.570093
Name: SalePrice, Length: 69, dtype: float64

ANOVA for state:
state
Alabama           38418.348067
Alaska            35157.085561
Arizona           37283.211169
Arkansas          31529.611880
California        32989.330312
Colorado          34389.673875
Connecticut       30205.869092
Delaware          35491.863517
Florida           36126.295796
Georgia           34713.598965
Hawaii            30572.500000
Idaho             31375.194301
Illinois          30536.564894
Indiana           25957.177364
Iowa              32479.196338
Kansas            30284.479554
Kentucky          32833.211054
Louisiana         32541.920095
Maine             28299.937965
Maryland          30671.974107
Massachusetts     31331.990521
Michigan          32963.636364
Minnesota         28353.647416
Mississippi       35626.463631
Missouri          31321.152409
Montana           34390.008726
Nebraska          33870.061728
Nevada            40609.574693
New Hampshire     29743.979176
New Jersey        33204.629621
New Mexico        37784.467341
New York          26661.439973
North Carolina    35231.220201
North Dakota      40741.160221
Ohio              30145.433996
Oklahoma          35718.773006
Oregon            31789.319853
Pennsylvania      27866.054919
Puerto Rico       29250.000000
Rhode Island      40034.677419
South Carolina    32128.014138
South Dakota      48129.670330
Tennessee         35197.650154
Texas             36677.108852
Unspecified       38214.887506
Utah              36336.697764
Vermont           28769.037657
Virginia          31279.118825
Washington        29465.963259
Washington DC     27000.000000
West Virginia     40911.343284
Wisconsin         29452.801190
Wyoming           34641.936051
Name: SalePrice, dtype: float64

ANOVA for ProductGroup:
ProductGroup
MG     47620.846827
SSL    10539.692173
TEX    35685.884174
TTT    36465.627335
WL     37142.817797
Name: SalePrice, dtype: float64

ANOVA for ProductGroupDesc:
ProductGroupDesc
Motor Graders          47620.846827
Skid Steer Loaders     10539.692173
Track Excavators       35685.884174
Track Type Tractors    36465.627335
Wheel Loader           37142.817797
Name: SalePrice, dtype: float64

ANOVA for Enclosure:
Enclosure
EROPS         30323.335142
EROPS w AC    54183.985713
OROPS         23604.568525
Name: SalePrice, dtype: float64

ANOVA for Hydraulics:
Hydraulics
2 Valve                36180.164471
3 Valve                44343.312662
4 Valve                56246.713287
Auxiliary              25109.170001
Base + 1 Function      46631.900975
Base + 2 Function      88069.105691
Base + 3 Function      84230.508475
Base + 4 Function      95073.333333
Base + 5 Function      74857.954545
Base + 6 Function      68581.632653
None or Unspecified    27400.000000
Standard               29054.307528
Name: SalePrice, dtype: float64

Positive correlation values indicate a positive relationship with the target variable, and negative values indicate a negative relationship. For categorical variables, ANOVA helps to understand if there are significant differences in the means of the target variable among different categories.

**i think we have a good view of our data so lets go to the next step which is `Data Prepairation`**